set shell := ["bash", "-cu"]

default:
  @just --list

install:
  bun install

dev:
  bun run dev

build:
  bun run build

start:
  bun run start

lint:
  bun run lint

fmt:
  bun run format

typecheck:
  bun run typecheck

check:
  bun run check

precommit-install:
  pre-commit install -c georg/.pre-commit-config.yaml --install-hooks

precommit-run:
  pre-commit run --all-files -c georg/.pre-commit-config.yaml
